version: 2
updates:

  # Check for GitHub Actions upgrades
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Check for Python dependency upgrades
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
