# See https://pre-commit.com for more information
default_language_version:
  ruby: '3.2.2'

# https://pre-commit.com/#supported-git-hooks
default_install_hook_types: # all of 'em!
  - commit-msg
  - post-checkout
  - post-commit
  - post-merge
  - post-rewrite
  - pre-commit
  - pre-merge-commit
  - pre-push
  - pre-rebase
  - prepare-commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pdm-project/pdm
    rev: '2.12.4'
    hooks:
      - id: pdm-lock-check
      - id: pdm-sync

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args:
          - "-r ~MD013"
