[tool.poetry]
name = "aoc-cj"
version = "0.1.0"
description = "cj81499's solutions for https://adventofcode.com/"
authors = ["Cal Jacobson <cj81499@users.noreply.github.com>"]
homepage = "https://github.com/cj81499/advent-of-code"

[tool.poetry.dependencies]
python = ">=3.9"
advent-of-code-data = "^1.3.2"
more-itertools = "^9.1.0"
numpy = "^1.24.3" # remove me
z3-solver = "^4.12.2"
lark = "^1.1.5"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pre-commit = "^3.3.2"
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
mypy = "^1.3"

[tool.poetry.plugins."adventofcode.user"]
cj81499 = "aoc_cj:solve"

[tool.black]
line_length = 120

[tool.coverage.run]
branch = true
parallel = true
omit = []

[tool.coverage.report]
exclude_lines = [
	'# pragma: no cover',
	'if __name__ == "__main__":',
	'if TYPE_CHECKING:',
  'raise NotImplementedError',
  '@abc\.abstractmethod',
  'assert False',
  'assert_never\(.*\)',
]

[tool.isort]
known_first_party = ["aoc_cj"]
line_length = 120
profile = "black"

[tool.pycln]
all = true

[tool.pytest.ini_options]
# skip slow tests by default
addopts = "-m 'not slow'"
markers = [
    "slow: marks tests as slow"
]
xfail_strict=true

[tool.mypy]
strict = true
# TODO: type check tests too
exclude = [
  '^tests\/aoc2015\/',
  '^tests\/aoc2016\/',
  '^tests\/aoc2017\/',
  '^tests\/aoc2018\/',
  '^tests\/aoc2019\/',
  '^tests\/aoc2020\/',
  '^tests\/aoc2021\/',
]
warn_unreachable = true

[[tool.mypy.overrides]]
module = ['aocd', 'aocd.models', 'z3']
ignore_missing_imports = true

# Opt out of type checking for old years.
# I may eventually go back and add types to these.
[[tool.mypy.overrides]]
module = [
    'aoc_cj.aoc2015.*',
    'aoc_cj.aoc2016.*',
    'aoc_cj.aoc2017.*',
    'aoc_cj.aoc2018.*',
    'aoc_cj.aoc2019.*',
    'aoc_cj.aoc2020.*',
]
ignore_errors = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
