[tool.poetry]
name = "aoc-cj"
version = "0.1.0"
description = "cj81499's solutions for https://adventofcode.com/"
authors = ["Cal Jacobson <cj81499@users.noreply.github.com>"]
homepage = "https://github.com/cj81499/advent-of-code-cj81499"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
advent-of-code-data = "^1.1.0"
lark-parser = "^0.12.0"
numpy = "^1.21.4" # remove me
parse = "^1.19.0" # remove me
z3-solver = "^4.8.12"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
pre-commit = "^2.15.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[tool.poetry.plugins."adventofcode.user"]
"cj81499" = "aoc_cj:solve"

[tool.black]
line_length = 120

[tool.isort]
known_first_party = ["aoc_cj"]
line_length = 120
profile = "black"

[tool.pycln]
all = true

[tool.pytest.ini_options]
# skip slow tests by default
addopts = "-m 'not slow'"
markers = [
    "slow: marks tests as slow"
]
xfail_strict=true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
