import aoc_cj.aoc2024.day08 as d

EXAMPLE_INPUT = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
""".strip()


def test_part_1() -> None:
    assert d.part_1(EXAMPLE_INPUT) == 14


def test_part_2() -> None:
    assert d.part_2(EXAMPLE_INPUT) == 34
