# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    env:
      AOC_SESSION: ${{ secrets.AOC_SESSION }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.*') }}-${{ hashFiles('*requirements.txt') }}

      - name: Use latest pip
        run: python -m pip install --upgrade pip

      - name: Install advent-of-code
        run: python -m pip install -e .

      - name: Test with pytest
        run: pytest
