name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.7

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          version: "0.4.10"

      - name: Create python venv
        run: uv venv --python ${{ matrix.python-version }}
        # if this doesn't work, try .python-version

      - name: Print Python version
        # https://docs.python.org/3/using/cmdline.html#cmdoption-version
        run: |
          which python3
          uv run python3 --version --version

      - name: Check format (ruff)
        run: uv run ruff format --check .

      - name: Lint (ruff)
        run: uv run ruff check --output-format=github .

      - name: Check types (mypy)
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
