name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          # - "3.13-dev"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.6

      - name: Set up PDM
        id: set-up-pdm
        uses: pdm-project/setup-pdm@v4.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pdm sync --dev

      - name: Check format (ruff)
        run: pdm run ruff format --check .

      - name: Lint (ruff)
        run: pdm run ruff check --output-format=github .

      - name: Check types (mypy)
        run: pdm run mypy .

      - name: Run tests
        run: pdm run pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
