name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.7

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          version: "0.4.10"

      - name: Pin python version to ${{ matrix.python-version }}
        run: uv python pin ${{ matrix.python-version }}

      - name: Sanity check Python version
        # https://docs.python.org/3/using/cmdline.html#cmdoption-version
        run: |
          uv run python --version --version
          [[ "$(uv run python --version | cut -d ' ' -f2)" =~ ^3\.12\.[0-9]+$ ]]

      - name: Check format (ruff)
        run: uv run ruff format --check .

      - name: Lint (ruff)
        run: uv run ruff check --output-format=github .

      - name: Check types (mypy)
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  check:
    if: always()
    runs-on: Ubuntu-latest
    needs:
    - build

    steps:
    - run: echo '${{ toJSON(needs) }}'

    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-failures: docs, linters
        allowed-skips: non-voting-flaky-job
        jobs: ${{ toJSON(needs) }}
