name: Update dependencies

on:
  schedule:
    - cron: "0 0 * * 0" # 00:00 on Sunday
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Update dependencies
        uses: pdm-project/update-deps-action@v1.9
        with:
          # A personal access token (PAT) must be used so that the created PR triggers CI
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          token: ${{ secrets.GH_TOKEN }}
