name: Update dependencies

on:
  schedule:
    - cron: "0 0 * * 0" # 00:00 on Sunday 
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Update dependencies
        uses: pdm-project/update-deps-action@main
